workflows:
  android-apk:
    name: Gerar APK do Quiz
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      vars:
        CM_ANDROID_SDK_VERSION: "33"
    triggering:
      events:
        - push
    scripts:
      - name: Compilar Jogo
        script: |
          cd jogo-top
          gradle assembleDebug
    artifacts:
      - jogo-top/app/build/outputs/apk/debug/*.apk
